//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blog.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class comment
    {
        public int Comment_id { get; set; }
        public Nullable<int> Article_id { get; set; }
        public string likes { get; set; }
        public string comment1 { get; set; }
        public Nullable<int> reward { get; set; }
        public Nullable<System.DateTime> comment_time { get; set; }
        public Nullable<int> operation_id { get; set; }
    
        public virtual Article Article { get; set; }
    }
}
